# use this to test-mount container builds

version: "2"
services:
  perforce:
    image: shukriadams/perforce-server:latest-2020
    container_name: myperforce
    restart: unless-stopped
    volumes:
      
      # core is where perforce's own files live. Never put depots in this. 
      # The name "MYSERVER" MUST match SERVER_NAME env var
      - ./../tmp/core:/opt/perforce/servers/MYSERVER/:rw

      # Put depots in here by default. 
      # When creating depots in P4Admin, nest each depot under this, egs: /opt/perforce/depots/MYDEPOT
      - ./depots:/opt/perforce/depots/:rw

      # DO NOT mount at an empty directory to this location, you will break your server. 
      # To get mountable config files, run your container once, this will generate config files and copy
      # them to ./core/config-mirror. Perforce ignores this copy, but you can copy them out to a 
      # directory of your choice, then enable this mount and at that directory.
      # - ./config/:/etc/perforce/:rw

    environment:
      # server name MUST match the name of the internal data volume folder above
      SERVER_NAME : MYSERVER

      # to disbale SSL use only "1666"
      P4PORT : ssl::1666    

      # used once when creating the admin p4user. After that, ignored.
      P4USER : perforce     

      # used once when creating the admin p4user. After that, ignored.
      P4PASSWD : Mypassword1 

      # must be defined, and must be in absolute server root dir
      P4SSLDIR: /opt/perforce/servers/MYSERVER/root/ssl 

      # used once when setting up server
      UNICODE: "true"

      # used once when setting up server
      CASE_SENSITIVE: "false"

      # if you want to set timezone on your container
      TZ: Etc/UTC

      # Allowed values : idle|maintenance
      # If blank, commented out or set to any other value, server will run in normal mode.
      # See onContainerStart.sh for how mode is used.
      # Note thatn when creating a new container instance, MODE cannot be "idle", as this will block the creation of default container content.
      # MODE: idle|maintenance

    ports:
    - "1666:1666"
