# use this to test-mount container builds

version: "2"
services:
  perforce:
    image: shukriadams/perforce-server:latest-2020
    container_name: perforce-test
    restart: unless-stopped
    volumes:
      # core is where perforce's own files live. Never put depots in this. 
      # The name "myserver" MUST match SERVER_NAME env var
      - ./../tmp/core:/opt/perforce/servers/myserver/:rw
      # Put depots in here by default. 
      # In P4Admin place your depot in /opt/perforce/depots/[your-depot-name-here]
      - ./../tmp/depots:/opt/perforce/depots/:rw
      # Do not mount this volume path when creating a new container installation, container must
      # run at least once without this mount to properly generate requried files
      # - ./config/:/etc/perforce/:rw
    environment:
      # server name MUST match the name of the internal data volume folder above
      SERVER_NAME : myserver
      # use "1666" to skip ssl
      P4PORT : ssl::1666 
      P4USER : perforce
      P4PASSWD : Mypassword1
      UNICODE: "true"
      CASE_SENSITIVE: "false"
      # When creating a new container instance, do not set START_MODE to idle. Idle blocks the creation of default container content.
      # START_MODE: maintenance
      TZ: Etc/UTC
    ports:
    - "1666:1666"
