# use this to test-mount container builds, for the a better example of a compose file see the file in project root.

version: "2"
services:
  perforce:
    image: shukriadams/perforce-server:latest-2020
    container_name: perforce-test
    restart: unless-stopped
    volumes:
      # core is where perforce's own files live. Never put depots in this. 
      # The name "myserver" MUST match SERVER_NAME env var
      - ./../tmp/core:/opt/perforce/servers/myserver/:rw
      # Put depots in here by default. 
      # In P4Admin place your depot in /opt/perforce/depots/[your-depot-name-here]
      - ./../tmp/depots:/opt/perforce/depots/:rw
      # Do not mount this volume path to an empty directory. The container must run at least once without
      # this mount to properly generate requried files. You can find those files in core/config-mirror, copy
      # them to a directory you want to mount, then restart your container mounting it.
      - ./config/:/etc/perforce/:rw
    environment:
      # server name MUST match the name of the internal data volume folder above
      SERVER_NAME : myserver
      P4PORT : ssl::1666  # use "1666" to skip ssl
      P4USER : perforce
      P4PASSWD : Mypassword1
      # must be defined, must be inside root/ssl, p4's ssl config is a brittlemess just accept it and move on
      P4SSLDIR: /opt/perforce/servers/myserver/root/ssl 
      FORCE_TRUST_AUTH: "true"
      UNICODE: "true"
      CASE_SENSITIVE: "false"
      # When creating a new container instance, do not set START_MODE to idle. Idle blocks the creation of default container content.
      # MODE: idle
      TZ: Etc/UTC
    ports:
    - "1666:1666"